/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RegVehicleInsuranceManagerRole;

import userinterface.RegLifeInsuranceManagerRole.*;
import userinterface.RegLifeInsuranceManagerRole.*;

import Business.EcoSystem;

import Business.Organizations.Organization;

import Business.WorkQueue.InsuranceProductWorkRequest;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */


public class ProcessWorkRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    InsuranceProductWorkRequest request;
    EcoSystem system ;
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ProcessWorkRequestJPanel(JPanel userProcessContainer, InsuranceProductWorkRequest request, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.system = system;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        resultJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        rejectJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        submitJButton.setBackground(new java.awt.Color(0, 0, 51));
        submitJButton.setForeground(new java.awt.Color(255, 255, 255));
        submitJButton.setText("Approve");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Comments");

        backJButton.setBackground(new java.awt.Color(0, 0, 51));
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        rejectJButton.setBackground(new java.awt.Color(0, 0, 51));
        rejectJButton.setForeground(new java.awt.Color(255, 255, 255));
        rejectJButton.setText("Reject");
        rejectJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addGap(58, 58, 58)
                        .addComponent(rejectJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submitJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitJButton)
                    .addComponent(backJButton)
                    .addComponent(rejectJButton))
                .addGap(169, 169, 169))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        VehicleInsuManagerWorkAreaJPane dwjp = (VehicleInsuManagerWorkAreaJPane) component;
        dwjp.populateTable();
        dwjp.populateBMTable();
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
       
        if (request.getStatus().equals("Completed")||((InsuranceProductWorkRequest)request).getApprovalStage().equals("61")) {
            JOptionPane.showMessageDialog(null, "Already Request Completed");
            return;
        }
        else  if (request.getStatus().equals("Rejected")|| ((InsuranceProductWorkRequest)request).getApprovalStage().equals("62")) {
            JOptionPane.showMessageDialog(null, "Already Rejected");
            return;
        }
        request.setTestResult(resultJTextField.getText());
        request.setStatus("Completed");
        ((InsuranceProductWorkRequest)request).setApprovalStage("61");
        Date dt = new Date ();
        request.setRequestDate(dt);
        
         Organization org = null;
         
        /*  for(Location  network : system.getNetworkList())
          { for(Enterprise entp : network.getEnterpriseDirectory().getEnterpriseList())
                {
                    if (entp.getEnterpriseType().equals(Enterprise.EnterpriseType.InsuranceRegulator) ){
                        entp.getWorkQueue().getWorkRequestList().add(request);
                         for (Organization organization :  entp.getOrganizaionDirectory().getOrganizationList()){
                                if (organization instanceof RegulatoryPolicyManagementOrganization ){
                                    org = organization;
                                    break;
                                }
        
                         }
                   }
              }
          }
       /*
        enterprise.getWorkQueue().getWorkRequestList().add(request);
        
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
           // userAccount.getWorkQueue().getWorkRequestList().add(request);
        } */
        JOptionPane.showMessageDialog(null, "Thank you !!");
        resultJTextField.setText("");
        
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void rejectJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectJButtonActionPerformed
        // TODO add your handling code here:
         if (request.getStatus().equals("Completed")) {
            JOptionPane.showMessageDialog(null, "Already Request Completed");
            return;
        }
        else  if (request.getStatus().equals("Rejected")) {
            JOptionPane.showMessageDialog(null, "Already Rejected");
            return;
        }
        request.setTestResult(resultJTextField.getText());
        request.setStatus("Rejected");
        ((InsuranceProductWorkRequest)request).setApprovalStage("62");
        JOptionPane.showMessageDialog(null, "Rejected.");
       
    }//GEN-LAST:event_rejectJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton rejectJButton;
    private javax.swing.JTextField resultJTextField;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
