/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Customer.Customer;
import Business.CustomerPolicy.Policy;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Location;
import Business.Organizations.CustomerAgentOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.Organizations.Organization;
import static Business.Organizations.Organization.Type.Customer;
import Business.WorkQueue.CustomerProductWorkRequest;
import Business.WorkQueue.InsuranceProductWorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class CustomerAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;

    private UserAccount userAccount;
    private EcoSystem system;

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public CustomerAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;

        this.userAccount = account;
        this.system = system;
        for (Customer cust : system.getCustomerDirectory().getCustomerList()) {
            if (cust.getUsername().equals(userAccount.getUsername())) {
                lblcustomername.setText("WelCome!! " + cust.getName());
                break;
            }
        }

        //valueLabel.setText(enterprise.getName());
        populateRequestTable();
        populateProductTable();
    }

    private void populateProductTable() {
        DefaultTableModel model = (DefaultTableModel) BMworkRequestJTable.getModel();

        model.setRowCount(0);
        for (Location network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.InsuranceCompany)) {
                    // for (Enterprise ent : enterprise.getOrganizaionDirectory().getOrganizationList()) {
                    for (WorkRequest request : enterprise.getWorkQueue().getWorkRequestList()) {
                        if (request != null) {
                            if (request.getClass().equals(Business.WorkQueue.InsuranceProductWorkRequest.class)) {
                                InsuranceProductWorkRequest iP = (InsuranceProductWorkRequest) request;
                                // InsuranceProductWorkRequest isr = wr;
                                if (iP.getApprovalStage() == null ? false : iP.getApprovalStage().equals("61")) {
                                    Object[] row = new Object[10];
                                    row[0] = iP.getNetwork();
                                    row[1] = iP.getEnterprise();
                                    row[3] = iP.getProductName();
                                    row[2] = iP.getInsuranceType();
                                    row[4] = iP.getPremuim();
                                    row[5] = iP.getProductDescription();
                                    row[6] = iP.getCoverageAmount();
                                    //row[7] = iP.getMessage();
                                    // row[8] = iP.getStatus();
                                    row[7] = iP;

                                    // row[9]=iP.
                                    model.addRow(row);
                                }
                            }
                        }
                        // }
                    }
                }

            }
        }

    }

    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            if (request.getClass().equals(CustomerProductWorkRequest.class)) {
                CustomerProductWorkRequest orderedProduct = (CustomerProductWorkRequest) request;
                Object[] row = new Object[4];
                row[0] = orderedProduct.getProductName();
                row[1] = orderedProduct.getInsuranceType();
                row[2] = orderedProduct.getStatus();
                // String result = ((LabTestWorkRequest) orderedProduct).getTestResult();
                // row[3] = result == null ? "Waiting" : result;

                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        refreshTestJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        BMworkRequestJTable = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        lblcustomername = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bestPlanBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(240, 166, 232));

        requestTestJButton.setBackground(new java.awt.Color(51, 0, 51));
        requestTestJButton.setForeground(new java.awt.Color(255, 255, 255));
        requestTestJButton.setText("Add to Cart");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });

        refreshTestJButton.setBackground(new java.awt.Color(51, 0, 51));
        refreshTestJButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });

        workRequestJTable.setAutoCreateRowSorter(true);
        workRequestJTable.setBackground(new java.awt.Color(255, 204, 204));
        workRequestJTable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 0, 51), new java.awt.Color(255, 153, 153)));
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Insurance", "Insurance Type", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.setGridColor(new java.awt.Color(255, 153, 204));
        workRequestJTable.setSelectionBackground(new java.awt.Color(51, 0, 51));
        jScrollPane2.setViewportView(workRequestJTable);

        BMworkRequestJTable.setAutoCreateRowSorter(true);
        BMworkRequestJTable.setBackground(new java.awt.Color(255, 204, 204));
        BMworkRequestJTable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 0, 51), new java.awt.Color(255, 153, 153)));
        BMworkRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Network", "Enterprise", "Type", "Name", "Premium", "Description", "Coverage Amount", "Request"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BMworkRequestJTable.setGridColor(new java.awt.Color(255, 204, 255));
        BMworkRequestJTable.setSelectionBackground(new java.awt.Color(51, 0, 51));
        jScrollPane4.setViewportView(BMworkRequestJTable);
        if (BMworkRequestJTable.getColumnModel().getColumnCount() > 0) {
            BMworkRequestJTable.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        lblcustomername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Insurance Plans:");

        bestPlanBtn.setBackground(new java.awt.Color(51, 0, 51));
        bestPlanBtn.setForeground(new java.awt.Color(255, 255, 255));
        bestPlanBtn.setText("Best Plan");
        bestPlanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestPlanBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bestPlanBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(refreshTestJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(requestTestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(45, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(462, 462, 462)
                .addComponent(lblcustomername, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(requestTestJButton)
                            .addComponent(refreshTestJButton)
                            .addComponent(bestPlanBtn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblcustomername, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBtn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        String menuItemName = "";
        // Restaurant restaurant;
        int selectedRow = BMworkRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please choose a plan.");
            return;
        }
        if (selectedRow >= 0) {
            //menuItemName = BMworkRequestJTable.getValueAt(selectedRow, 0).toString();
            // Enterprise enterprise = (Enterprise) BMworkRequestJTable.getValueAt(selectedRow, 1);
            InsuranceProductWorkRequest request = (InsuranceProductWorkRequest) BMworkRequestJTable.getValueAt(selectedRow, 7);
            //  InsuranceProductWorkRequest custRequest = (InsuranceProductWorkRequest) BMworkRequestJTable.getValueAt(selectedRow, 7);
            if (request.getClass().equals(InsuranceProductWorkRequest.class)) {
                CustomerProductWorkRequest custRequest = new CustomerProductWorkRequest();
                custRequest.setApprovalStage(request.getApprovalStage());
                custRequest.setCoverageAmount(request.getCoverageAmount());
                custRequest.setEnterprise(request.getEnterprise());
                custRequest.setInsuranceType(request.getInsuranceType());
                custRequest.setNetwork(request.getNetwork());
                custRequest.setPremuim(request.getPremuim());
                custRequest.setProductDescription(request.getProductDescription());
                custRequest.setProductName(request.getProductName());
                //custRequest.setRequestDate(daet);
                custRequest.setSender(userAccount);

                // custRequest.getProductDescription().contains("");
                custRequest.setApprovalStage("0");

                for (Policy policy : system.getCustPolicyDirectory().getPolicyList()) {
                    if (policy.getName().equals(request.getProductName()) && policy.getCustomerName().equals(userAccount.getUsername())) {
                        JOptionPane.showMessageDialog(null, "Sorry!! cannot place your order as You already have this policy");
                        return;
                    }
                }

                Organization org = null;

                for (Location network : system.getNetworkList()) {
                    for (Enterprise entp : network.getEnterpriseDirectory().getEnterpriseList()) {
                        if (entp.getEnterpriseType().getValue().equals(Enterprise.EnterpriseType.InsuranceBroker.getValue())) {
                            entp.getWorkQueue().getWorkRequestList().add(custRequest);
                            for (Organization organization : entp.getOrganizaionDirectory().getOrganizationList()) {
                                if (organization instanceof CustomerAgentOrganization) {
                                    org = organization;
                                    break;
                                }

                            }
                        }
                    }
                }

                if (org != null) {
                    org.getWorkQueue().getWorkRequestList().add(custRequest);
                    custRequest.setStatus("Order Placed");
                    userAccount.getWorkQueue().getWorkRequestList().add(custRequest);
                } else {
                    JOptionPane.showMessageDialog(null, "Sorry!! cannot place your order at this time.Could not found the further approval organization.");
                }
            }
        }
        populateRequestTable();


    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed
        txtSearch.setText("");
        populateProductTable();
        populateRequestTable();

    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        // String s= "the of name desc 30 life health dental";
        //  boolean flag = s.contains("dental");

        DefaultTableModel model = (DefaultTableModel) BMworkRequestJTable.getModel();

        model.setRowCount(0);
        for (Location network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.InsuranceCompany)) {
                    // for (Enterprise ent : enterprise.getOrganizaionDirectory().getOrganizationList()) {
                    for (WorkRequest request : enterprise.getWorkQueue().getWorkRequestList()) {
                        if (request != null) {
                            if (request.getClass().equals(Business.WorkQueue.InsuranceProductWorkRequest.class)) {
                                InsuranceProductWorkRequest iP = (InsuranceProductWorkRequest) request;
                                // InsuranceProductWorkRequest isr = wr;
                                if (iP.getApprovalStage() == null ? false : iP.getApprovalStage().equals("61")) {
                                    if (iP.getNetwork().getName().toLowerCase().contains(txtSearch.getText().toLowerCase())
                                            || iP.getEnterprise().getName().toLowerCase().contains(txtSearch.getText().toLowerCase())
                                            || iP.getProductName().toLowerCase().contains(txtSearch.getText().toLowerCase())
                                            || iP.getProductDescription().toLowerCase().contains(txtSearch.getText().toLowerCase())
                                            || iP.getPremuim().toLowerCase().contains(txtSearch.getText().toLowerCase())
                                            || iP.getCoverageAmount().toLowerCase().contains(txtSearch.getText().toLowerCase())
                                            || iP.getInsuranceType().getValue().toLowerCase().contains(txtSearch.getText().toLowerCase())) {

                                        Object[] row = new Object[10];
                                        row[0] = iP.getNetwork();
                                        row[1] = iP.getEnterprise();
                                        row[3] = iP.getProductName();
                                        row[2] = iP.getInsuranceType();
                                        row[4] = iP.getPremuim();
                                        row[5] = iP.getProductDescription();
                                        row[6] = iP.getCoverageAmount();
                                        //row[7] = iP.getMessage();
                                        // row[8] = iP.getStatus();
                                        row[7] = iP;

                                        // row[9]=iP.
                                        model.addRow(row);
                                    }
                                }
                            }
                        }
                        // }
                    }
                }

            }
        }


    }//GEN-LAST:event_searchBtnActionPerformed

    private void bestPlanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestPlanBtnActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) BMworkRequestJTable.getModel();

        model.setRowCount(0);
        InsuranceProductWorkRequest bestplan = null;
        int previousprofit = 0;
        for (Location network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.InsuranceCompany)) {
                    // for (Enterprise ent : enterprise.getOrganizaionDirectory().getOrganizationList()) {
                    for (WorkRequest request : enterprise.getWorkQueue().getWorkRequestList()) {
                        if (request != null) {
                            if (request.getClass().equals(Business.WorkQueue.InsuranceProductWorkRequest.class)) {
                                InsuranceProductWorkRequest iP = (InsuranceProductWorkRequest) request;
                                // InsuranceProductWorkRequest isr = wr;
                                if (iP.getApprovalStage() == null ? false : iP.getApprovalStage().equals("61")) {
                                    if (iP.getNetwork().getName().toLowerCase().contains(txtSearch.getText().toLowerCase())
                                            || iP.getEnterprise().getName().toLowerCase().contains(txtSearch.getText().toLowerCase())
                                            || iP.getProductName().toLowerCase().contains(txtSearch.getText().toLowerCase())
                                            || iP.getProductDescription().toLowerCase().contains(txtSearch.getText().toLowerCase())
                                            || iP.getPremuim().toLowerCase().contains(txtSearch.getText().toLowerCase())
                                            || iP.getCoverageAmount().toLowerCase().contains(txtSearch.getText().toLowerCase())
                                            || iP.getInsuranceType().getValue().toLowerCase().contains(txtSearch.getText().toLowerCase())) {
                                        int coverage = Integer.parseInt(iP.getCoverageAmount());
                                        int Premuim = Integer.parseInt(iP.getPremuim());
                                        int profit = coverage / Premuim;
                                        if (profit > previousprofit) {
                                            bestplan = iP;
                                            previousprofit = profit;
                                        }
                                    }
                                }
                            }
                        }
                        // }
                    }
                }

            }
        }
        if (bestplan != null) {
            Object[] row = new Object[10];
            row[0] = bestplan.getNetwork();
            row[1] = bestplan.getEnterprise();
            row[3] = bestplan.getProductName();
            row[2] = bestplan.getInsuranceType();
            row[4] = bestplan.getPremuim();
            row[5] = bestplan.getProductDescription();
            row[6] = bestplan.getCoverageAmount();
            //row[7] = iP.getMessage();
            // row[8] = iP.getStatus();
            row[7] = bestplan;
            model.addRow(row);
        }

    }//GEN-LAST:event_bestPlanBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BMworkRequestJTable;
    private javax.swing.JButton bestPlanBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblcustomername;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
